4. Workshop 1/Petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Petstagram.common.urls')),
    path('accounts/', include('Petstagram.accounts.urls')),
    path('pets/', include('Petstagram.pets.urls')),
    path('photos/', include('Petstagram.photos.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4. Workshop 1/Petstagram/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from Petstagram.photos.models import PetPhoto

UserModel = get_user_model()


class PhotoComment(models.Model):
    MAX_TEXT_LENGTH = 300

    text = models.TextField(
        max_length=MAX_TEXT_LENGTH,
        null=False,
        blank=False,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
    )

    pet_photo = models.ForeignKey(
        PetPhoto,
        on_delete=models.RESTRICT,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )


class PhotoLike(models.Model):
    pet_photo = models.ForeignKey(
        PetPhoto, on_delete=models.DO_NOTHING,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

# photo_like = PhotoLike.objects.filter(pet_photo_id=pet_photo.pk, user=request.user)

4. Workshop 1/templates/partials/pet-list-item.html
{% load static %}

<div class="card">
                <div class="top">
                    <div class="userDetails">
                        <a href="{% url 'details profile' pk=1 %}">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static '/images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>
                            <a href="{% url 'details profile' pk=1 %}">
                                Doncho
                            </a>
                            <br>
                            <span>{{ photo.location }}</span>
                        </h3>
                    </div>
                </div>

                <div class="imgBx" id="photo-{{ photo.pk }}">
                    {# Hard coded, because I do not have url field in my PetPhoto model #}
                    <img src="{% static '/images/cat-photo.jpg' %}" alt="post" class="cover">
                    {# <img src="{{ photo.photo.url }}" alt="post" class="cover" #}
                </div>

                <div class="bottom">
                    <div class="actionBtns">
                        <div class="left">
                            <span class="heart">
                                <a href="{% url 'like pet photo' pk=photo.pk %}">
                                    {% if photo.photolike_set.count > 0 %}
                                    <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                                    {% else %}
                                    <i class="fa-regular fa-heart"></i>
                                    {% endif %}
                                </a>
                            </span>

                            <a href="#">
                                <i class="fa-solid fa-share"></i>
                            </a>

                        </div>
                    </div>

                    <p class="likes">{{ photo.photolike_set.count }} likes</p>

                    {% for pet in photo.pets.all %}    {# This does not execute the QuerySet #}
                    <a href="{% url 'details pet' username='Doncho' pet_slug=pet.slug %}">
                        <p class="message">
                            <b>{{ pet.name }}</b>
                        </p>
                    </a>
                    {% endfor %}

                    <a href="{% url 'details photo' pk=photo.pk %}">
                        <h4 class="details">See details</h4>
                    </a>

                    <!-- Date of Publication -->
                    <h5 class="postTime">19/09/2022</h5>
                    {# <h5 class=postTime">{{ photo.created_at|date: 'd/m/Y }}</h5> #}

                    <!-- Start Add Comments Section -->
                    <div class="addComments">

                        <form method="post" action="#">
                            <label for="id_body">Body:</label>
                            <textarea name="body" cols="40" rows="10" placeholder="Add comment" maxlength="300"
                                      required="" id="id_body"></textarea>
                            <button type="submit">Post</button>
                        </form>

                    </div>

                </div>
            </div>

4. Workshop 1/templates/partials/pets-photos-list.html
{% load static %}

{% for photo in photo_list %}
    {% include "partials/pet-list-item.html" with photo=photo %}

{% empty %}
    <img class="no-posts" src="{% static '/images/no_posts.png' %}" alt="no posts image">
{% endfor %}